Repository kiritigowda/MIVisionX-Validation-Tool, pull requests merged in 2019-10, with the labels that each got.

#7 H/display gui
  inference_control.ui
  inference_viewer.py
  inference_viewer.ui
  mivisionx_validation_tool.py
Labels: BugFix

#14 H/display gui
  data/images/AMD_Radeon-white.png
  data/images/AMD_Radeon.png
  inference_control.ui
  inference_viewer.py
  inference_viewer.ui
  mivisionx_validation_tool.py
  test.ui
Labels: enhancement

#29 Bug Fix
  README.md
  inference_control.py
  inference_viewer.py
  mivisionx_validation_tool.py
Labels: BugFix

#30 H/display gui
  inference_control.py
  inference_control.ui
  inference_viewer.py
  inference_viewer.ui
  mivisionx_validation_tool.py
Labels: BugFix, new version
